---
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
  - name: create new droplet
    digital_ocean:
      state: present
      command: droplet
      name: ansible-test
      private_networking: yes
      size_id: 512mb
      image_id: centos-7-x64
      region_id: nyc1
      ssh_key_ids: 7632942
      unique_name: yes
    register: do

  - debug: var=do

  - name: add new host to our inventory
    add_host:
      name: "{{ do.droplet.ip_address }}"
      groups: do
    when: do.droplet is defined

- hosts: do
  remote_user: root
  gather_facts: false

  tasks:
  - name: wait for port 22 to become available
    local_action: "wait_for port=22 host={{ inventory_hostname }}"

  - name: install tcpdump
    yum: name=tcpdump state=present
